#!/bin/bash

# defaults
duration=1000

longopts="duration:"
opts=$(getopt -q -o "D:" --longoptions "$longopts" -n "getopt.sh" -- "$@");
eval set -- "$opts";
while true; do
    case "$1" in
        -D|--duration)
            shift
            duration=$1
            shift
            ;;
        --)
            shift;
            break
            ;;
        *)
            shift
            ;;
    esac
done

#echo "$duration"
echo 1200
