#!/bin/bash

exec >flexran-server.log
exec 2>&1

. /usr/bin/flexran-base || (echo "/usr/bin/flexran-base not found"; exit 1)
dump_runtime
validate_label
validate_sw_prereqs

echo "enter flexran-server-start"
echo "opts; $@"

xran_devices=""
cc_num=0
longopts="xran-devices:,cc-num:"
opts=$(getopt -q -o "" --longoptions "$longopts" -n "getopt.sh" -- "$@");
if [ $? -ne 0 ]; then
    exit_error "Unrecognized option specified"
fi
eval set -- "$opts";
while true; do
    case "$1" in
    --xran-devices)
        shift;
        xran_devices=$1
        #export PCIDEVICE_OPENSHIFT_IO_INTELNICS0=$1
        shift;
        ;;
    --cc-num)
        # For DEBUG, we may vary number of cells to change processing loads
        shift;
        cc_num=$1
        shift;
        ;;
    --)
        shift;
        break
        ;;
    *)
        exit_error "Unsupport option $1"
        break
        ;;
    esac
done


if [ "$xran_devices" != "" ]; then    
    log_file=$(realpath flexran-server.log)
    pushd /tmp/script-dir 
    if [ "$cc_num" != 0 ]; then
        source  /opt/flexran/cru_env_vars.sh
        sed -i 's/ccNum=.*/ccNum='${cc_num}'/' ${ORU_DIR}/config_file_o_ru.dat
    fi
    # Part of the testbed provisioning, we must have run "./08-ru_sriov.sh setup". Now we run "config"
    ./08-ru_sriov.sh config
    ./09-ru_start.sh ${log_file}
    popd 
fi


