#!/bin/bash

function exit_error() {
    local msg="$1"; shift
    local code="$1"; shift
    if [ -z "$code" ]; then
        code=1
    fi
    echo '{"recipient":{"type":"all","id":"all"},"user-object":{"error": "'$msg'"}}' >msgs/tx/error
    echo "$msg"
    exit $code
}

function dump_runtime() {
    echo env:
    env
    echo
    echo "args: $@"
    echo
    echo "pwd:"
    /bin/pwd
    echo
    echo "ls -alR:"
    ls -alR
    echo
    echo "hostname: `hostname`"
    echo
    echo filesystems:
    mount
    echo
    echo "ls -l /dev/hugepages"
    /bin/ls -l /dev/hugepages
    echo
    echo "/proc/meminfo"
    cat /proc/meminfo
    echo
    echo netdevs:
    ls -l /sys/class/net
    echo
    echo ip a:
    ip a
    echo
    echo "per-node-hugepages:"
    for n in 0 1; do
        path="/sys/devices/system/node/node$n/hugepages/hugepages-1048576kB"
        echo $path
        for i in `/bin/ls -1 $path`; do
            echo $i:
            cat $path/$i
        done
    done
    echo "cpumask"
    taskset -pc $$
}

function validate_label() {
    id=`echo $RS_CS_LABEL | awk -F- '{print $2}'`
    re='^[1-9][0-9]*$'
    if [[ ! "$id" =~ $re ]]; then
        exit_error "ID from label $RS_CS_LABEL must a be a positive interger"
    fi
}

function validate_sw_prereqs() {
    local missing=""
    local bail=0
    echo "Checking for SW deps"
    bin="getopt"
    if $bin -V >/dev/null 2>&1; then
        echo "Found $bin"
    else
        bail=1
        missing+=" $bin"
    fi
    # ip does not like -h
    bin="ip"
    if $bin a >/dev/null 2>&1; then
        echo "Found $bin"
    else
        bail=1
        missing+=" $bin"
    fi
    if [ $bail -eq 1 ]; then
        exit_error "Could not find bin: $missing"
    fi
}

