#!/bin/bash
# mode will be set as LTE or 5G
MODE=$1
if [ "$MODE" == "LTE" ]; then
	echo "Crucible does not support LTE"
	exit 1

elif [ "$MODE" != "5G" ]; then
	echo "Crucible only support 5G"
	exit 1
fi

source /opt/flexran_env_vars.sh

if [ -n "$TESTFILE" ]; then
    if [ "$TESTFILE" != "none" ]; then
	    echo "CRU: invoke ./flexran-pic-l2 --testfile=${TESTFILE}"
	    ./flexran-pic-l2 --testfile=${TESTFILE}
    else
	    echo "CRU: invoke ./flexran-pic-l2"
	    ./flexran-pic-l2 
    fi
else
	echo "CRU: invoke ./flexran-pic-l1 -e"
	./flexran-pic-l1 -e
fi

